[build]
  command = "npm run build"
  publish = "dist"

# Redirect docs to separate Netlify project
# ("ninjaterm-docs")
[[redirects]]
  from = "/docs/*"
  to = "https://ninjaterm-docs.netlify.app/:splat"
  status = 200

# This is needed for react-router to work,
# otherwise you get 404s
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
